### ISSUE TITLE
Words that are unlikely to be offensive are flagged as offensive.

### ISSUE THREAD

**Issue by just3ws** [wooorm/retext-profanities#16]
> There are many colors in the rainbow.

> The sky was colored blue as the sea.

Those words are being flagged as offensive. Looking at https://github.com/words/cuss/blob/7f4175b198d6428a4d4140b157825cf75185001b/index.json they are also flagged as being "unlikely". 

Might the list be more effective in identifying harmful language if it were dialed down to words that are likely to be offensive?

**Comment by Murderlon** [comment]
Hi! I'm not sure which words you mean specifically but I'm guessing "colors" and "colored".

So [`cuss`](https://github.com/words/cuss) actually tries to be more effective by providing an exhaustive list with how likely words could be used as either profane **or clean text**. In this case the words you mentioned are very unlikely to be profane but it is possible and therefor makes it into the list.

**Comment by wooorm** [comment]
@just3ws Yep, as @Murderlon points out, this is actually a feature that this package has over other projects, by using those cuss ratings. We also add that value [to each message](https://github.com/retextjs/retext-profanities/blob/055b7432505c986dc8da4ce77723bd7076e2bbd1/factory.js#L76), so you could filter out the messages with a score of `0` (unlikely to be profanities) if you’re so inclined.

**Comment by just3ws** [comment]
Okay, thanks for your response. :)
